POST http://localhost:8080/v1/authenticate
Accept: application/json
Content-Type: application/json

{
  "user": "user1"
}

###
POST http://localhost:8080/v1/stream-credentials
Authorization: Bearer cGcuODLKQ8K+pD4LpxsL/APBRmh9wg0S8bIu4Wla8As=
Accept: application/json
Content-Type: application/json

{}

###
POST http://localhost:8080/v1/virgil-credentials
Authorization: Bearer cGcuODLKQ8K+pD4LpxsL/APBRmh9wg0S8bIu4Wla8As=
Accept: application/json
Content-Type: application/json

{}

###
