POST http://localhost:8080/v1/authenticate
Accept: application/json
Content-Type: application/json

{
  "user": "user1"
}

###
POST http://localhost:8080/v1/stream-credentials
Authorization: Bearer 82Jg4bDN8cu6XWIX5EIVCpeKpFMGflKB9BW7aZkWWyw=
Accept: application/json
Content-Type: application/json

{}

###
POST http://localhost:8080/v1/virgil-credentials
Authorization: Bearer 82Jg4bDN8cu6XWIX5EIVCpeKpFMGflKB9BW7aZkWWyw=
Accept: application/json
Content-Type: application/json

{}

###
